import { DriveType, VehicleProps } from "../types/VehicleTypes";
import civic from "../assets/VehicleImages/civic.png";
import tundra from "../assets/VehicleImages/tundra.png";
import sportage from "../assets/VehicleImages/sportage.png";
import accord from "../assets/VehicleImages/accord.png";
import outback from "../assets/VehicleImages/outback.png";
import highlander from "../assets/VehicleImages/highlander.png";
import forester from "../assets/VehicleImages/forester.png";
import crosstrek from "../assets/VehicleImages/crosstrek.png";
import taco from "../assets/VehicleImages/taco.png";
import explorer from "../assets/VehicleImages/explorer.png";
import trax from "../assets/VehicleImages/trax.png";
import tucson from "../assets/VehicleImages/tucson.png";
import equinox from "../assets/VehicleImages/equinox.png";
import jgc from "../assets/VehicleImages/jgc.png";
import corolla from "../assets/VehicleImages/corolla.png";
import rogue from "../assets/VehicleImages/rogue.png";
import camry from "../assets/VehicleImages/camry.png";
import sierra from "../assets/VehicleImages/sierra.png";
import ram from "../assets/VehicleImages/ram.png";
import crv from "../assets/VehicleImages/crv.png";
import my from "../assets/VehicleImages/my.png";
import rav4 from "../assets/VehicleImages/rav4.png";
import silverado from "../assets/VehicleImages/silverado.png";
import f150 from "../assets/VehicleImages/f150.png";

export const vehicles: VehicleProps[] = [
  {
    make: "Honda",
    model: "Civic",
    zeroToSixty: "7.5 seconds",
    topSpeed: "130 mph",
    fuelEconomy: {
      city: "30",
      highway: "38",
      combined: "33",
    },
    powertrain: {
      horsepower: "180",
      torque: "177",
      displacement: "1.5L Turbo",
      gearing: "Continuously Variable",
      type: "Automatic",
    },
    bodyStyle: "Hatchback",
    sizeClass: "Compact",
    driveType: DriveType.fwd,
    imageSrc: civic,
    intrinsicAttributeArray: [4, 5, 2, 7, 5],
  },
  {
    make: "Toyota",
    model: "Tundra",
    zeroToSixty: "6.1 seconds",
    topSpeed: "108 mph",
    fuelEconomy: {
      city: "17",
      highway: "22",
      combined: "19",
    },
    powertrain: {
      horsepower: "389",
      torque: "479",
      displacement: "3.4L Twin Turbo",
      gearing: "10-Speed",
      type: "Automatic",
    },
    bodyStyle: "Truck",
    sizeClass: "Full Size",
    driveType: DriveType.fourByFour,
    imageSrc: tundra,
    intrinsicAttributeArray: [5, 4, 9, 3, 5],
  },
  {
    make: "Kia",
    model: "Sportage",
    zeroToSixty: "9.1 seconds",
    topSpeed: "120 mph",
    fuelEconomy: {
      city: "23",
      highway: "30",
      combined: "26",
    },
    powertrain: {
      horsepower: "187",
      torque: "178",
      displacement: "2.5L",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: sportage,
    intrinsicAttributeArray: [1, 3, 6, 5, 4],
  },
  {
    make: "Honda",
    model: "Accord",
    zeroToSixty: "6.7 seconds",
    topSpeed: "125 mph",
    fuelEconomy: {
      city: "41",
      highway: "46",
      combined: "44",
    },
    powertrain: {
      horsepower: "204",
      torque: "247",
      displacement: "2.0L Hybrid",
      capacity: "1.1 kwh",
      range: "4 miles",
      gearing: "Continuously Variable",
      type: "Automatic",
    },
    bodyStyle: "Sedan",
    sizeClass: "Midsize",
    driveType: DriveType.fwd,
    imageSrc: accord,
    intrinsicAttributeArray: [5, 5, 6, 8, 5],
  },
  {
    make: "Subaru",
    model: "Outback",
    zeroToSixty: "8.5 seconds",
    topSpeed: "115 mph",
    fuelEconomy: {
      city: "26",
      highway: "32",
      combined: "28",
    },
    powertrain: {
      horsepower: "182",
      torque: "176",
      displacement: "2.5L",
      gearing: "Contunuously Variable",
      type: "Automatic",
    },
    bodyStyle: "Wagon",
    sizeClass: "Full Size",
    driveType: DriveType.awd,
    imageSrc: outback,
    intrinsicAttributeArray: [1, 3, 7, 5, 5],
  },
  {
    make: "Toyota",
    model: "Highlander",
    zeroToSixty: "7.2 seconds",
    topSpeed: "113 mph",
    fuelEconomy: {
      city: "21",
      highway: "28",
      combined: "24",
    },
    powertrain: {
      horsepower: "265",
      torque: "310",
      displacement: "2.4L Turbo",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Full Size",
    driveType: DriveType.awd,
    imageSrc: highlander,
    intrinsicAttributeArray: [4, 3, 7, 6, 5],
  },
  {
    make: "Subaru",
    model: "Forester",
    zeroToSixty: "8.3 seconds",
    topSpeed: "127 mph",
    fuelEconomy: {
      city: "25",
      highway: "32",
      combined: "28",
    },
    powertrain: {
      horsepower: "180",
      torque: "178",
      displacement: "2.5L",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: forester,
    intrinsicAttributeArray: [1, 3, 6, 5, 4],
  },
  {
    make: "Subaru",
    model: "Crosstrek",
    zeroToSixty: "9.5 seconds",
    topSpeed: "120 mph",
    fuelEconomy: {
      city: "27",
      highway: "34",
      combined: "29",
    },
    powertrain: {
      horsepower: "180",
      torque: "178",
      displacement: "2.5L",
      gearing: "Continuously Variable",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: crosstrek,
    intrinsicAttributeArray: [0, 3, 6, 4, 4],
  },
  {
    make: "Toyota",
    model: "Tacoma",
    zeroToSixty: "7.0 seconds",
    topSpeed: "106 mph",
    fuelEconomy: {
      city: "19",
      highway: "23",
      combined: "20",
    },
    powertrain: {
      horsepower: "278",
      torque: "317",
      displacement: "2.4L Turbo",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "Truck",
    sizeClass: "Midsize",
    driveType: DriveType.fourByFour,
    imageSrc: taco,
    intrinsicAttributeArray: [3, 5, 6, 6, 7],
  },
  {
    make: "Ford",
    model: "Explorer",
    zeroToSixty: "6.0 seconds",
    topSpeed: "113 mph",
    fuelEconomy: {
      city: "19",
      highway: "22",
      combined: "21",
    },
    powertrain: {
      horsepower: "300",
      torque: "310",
      displacement: "2.2L Turbo",
      gearing: "10-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Full Size",
    driveType: DriveType.awd,
    imageSrc: explorer,
    intrinsicAttributeArray: [5, 5, 7, 6, 5],
  },
  {
    make: "Chevy",
    model: "Trax",
    zeroToSixty: "8.8 seconds",
    topSpeed: "115 mph",
    fuelEconomy: {
      city: "28",
      highway: "32",
      combined: "30",
    },
    powertrain: {
      horsepower: "137",
      torque: "162",
      displacement: "1.2L Turbo",
      gearing: "6-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Subcompact",
    driveType: DriveType.fwd,
    imageSrc: trax,
    intrinsicAttributeArray: [2, 4, 4, 5, 5],
  },
  {
    make: "Hyundai",
    model: "Tucson",
    zeroToSixty: "8.8 seconds",
    topSpeed: "120 mph",
    fuelEconomy: {
      city: "24",
      highway: "29",
      combined: "26",
    },
    powertrain: {
      horsepower: "187",
      torque: "178",
      displacement: "2.5L",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: tucson,
    intrinsicAttributeArray: [3, 5, 7, 5, 6],
  },
  {
    make: "Chevrolet",
    model: "Equinox",
    zeroToSixty: "8.0 seconds",
    topSpeed: "125 mph",
    fuelEconomy: {
      city: "24",
      highway: "30",
      combined: "26",
    },
    powertrain: {
      horsepower: "175",
      torque: "203",
      displacement: "1.5L Turbo",
      gearing: "6-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: equinox,
    intrinsicAttributeArray: [3, 5, 7, 5, 5],
  },
  {
    make: "Jeep",
    model: "Grand Cherokee",
    zeroToSixty: "7.4 seconds",
    topSpeed: "117 mph",
    fuelEconomy: {
      city: "19",
      highway: "26",
      combined: "22",
    },
    powertrain: {
      horsepower: "293",
      torque: "260",
      displacement: "3.6L",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: jgc,
    intrinsicAttributeArray: [6, 7, 7, 5, 7],
  },
  {
    make: "Toyota",
    model: "Corolla",
    zeroToSixty: "8.3 seconds",
    topSpeed: "114 mph",
    fuelEconomy: {
      city: "32",
      highway: "42",
      combined: "36",
    },
    powertrain: {
      horsepower: "168",
      torque: "151",
      displacement: "2.0L",
      gearing: "Continuously Variable",
      type: "Automatic",
    },
    bodyStyle: "Hatchback",
    sizeClass: "Compact",
    driveType: DriveType.fwd,
    imageSrc: corolla,
    intrinsicAttributeArray: [4, 5, 3, 4, 5],
  },
  {
    make: "Nissan",
    model: "Rogue",
    zeroToSixty: "8.0 seconds",
    topSpeed: "120 mph",
    fuelEconomy: {
      city: "28",
      highway: "34",
      combined: "31",
    },
    powertrain: {
      horsepower: "201",
      torque: "225",
      displacement: "1.5L",
      gearing: "Continuously Variable",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: rogue,
    intrinsicAttributeArray: [4, 5, 7, 5, 5],
  },
  {
    make: "Toyota",
    model: "Camry",
    zeroToSixty: "6.8 seconds",
    topSpeed: "115 mph",
    fuelEconomy: {
      city: "44",
      highway: "44",
      combined: "43",
    },
    powertrain: {
      horsepower: "232",
      torque: "225",
      displacement: "2.5L Hybrid",
      capacity: "0.6 kwh",
      range: "2 miles",
      gearing: "Continuously Variable",
      type: "Automatic",
    },
    bodyStyle: "Sedan",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: camry,
    intrinsicAttributeArray: [5, 5, 7, 8, 5],
  },
  {
    make: "GMC",
    model: "Sierra",
    zeroToSixty: "5.4 seconds",
    topSpeed: "106 mph",
    fuelEconomy: {
      city: "15",
      highway: "20",
      combined: "17",
    },
    powertrain: {
      horsepower: "420",
      torque: "460",
      displacement: "6.1L",
      gearing: "10-Speed",
      type: "Automatic",
    },
    bodyStyle: "Truck",
    sizeClass: "Full Size",
    driveType: DriveType.fourByFour,
    imageSrc: sierra,
    intrinsicAttributeArray: [6, 6, 9, 4, 5],
  },
  {
    make: "Ram",
    model: "1500",
    zeroToSixty: "4.2 seconds",
    topSpeed: "106 mph",
    fuelEconomy: {
      city: "15",
      highway: "21",
      combined: "17",
    },
    powertrain: {
      horsepower: "540",
      torque: "521",
      displacement: "3.0L Twin Turbo",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "Truck",
    sizeClass: "Full Size",
    driveType: DriveType.fourByFour,
    imageSrc: ram,
    intrinsicAttributeArray: [8, 6, 9, 2, 5],
  },
  {
    make: "Honda",
    model: "CR-V",
    zeroToSixty: "8.1 seconds",
    topSpeed: "130 mph",
    fuelEconomy: {
      city: "27",
      highway: "32",
      combined: "29",
    },
    powertrain: {
      horsepower: "190",
      torque: "179",
      displacement: "1.5L Turbo",
      gearing: "Continuously Variable",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: crv,
    intrinsicAttributeArray: [3, 4, 5, 4, 3],
  },
  {
    make: "Tesla",
    model: "Model Y",
    zeroToSixty: "4.4 seconds",
    topSpeed: "136 mph",
    fuelEconomy: {
      city: "129",
      highway: "112",
      combined: "121",
    },
    powertrain: {
      horsepower: "384",
      torque: "376",
      capacity: "80.5 kwh",
      range: "310 miles",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: my,
    intrinsicAttributeArray: [7, 8, 5, 6, 6],
  },
  {
    make: "Toyota",
    model: "RAV4",
    zeroToSixty: "8.3 seconds",
    topSpeed: "119 mph",
    fuelEconomy: {
      city: "25",
      highway: "32",
      combined: "28",
    },
    powertrain: {
      horsepower: "203",
      torque: "184",
      displacement: "2.5L",
      gearing: "8-Speed",
      type: "Automatic",
    },
    bodyStyle: "SUV",
    sizeClass: "Midsize",
    driveType: DriveType.awd,
    imageSrc: rav4,
    intrinsicAttributeArray: [4, 5, 6, 3, 4],
  },
  {
    make: "Chevrolet",
    model: "Silverado",
    zeroToSixty: "5.4 seconds",
    topSpeed: "112 mph",
    fuelEconomy: {
      city: "16",
      highway: "21",
      combined: "18",
    },
    powertrain: {
      horsepower: "420",
      torque: "460",
      displacement: "6.1L",
      gearing: "10-Speed",
      type: "Automatic",
    },
    bodyStyle: "Truck",
    sizeClass: "Full Size",
    driveType: DriveType.fourByFour,
    imageSrc: silverado,
    intrinsicAttributeArray: [7, 5, 8, 3, 4],
  },
  {
    make: "Ford",
    model: "F-150",
    zeroToSixty: "6.0 seconds",
    topSpeed: "102 mph",
    fuelEconomy: {
      city: "15",
      highway: "20",
      combined: "17",
    },
    powertrain: {
      horsepower: "400",
      torque: "410",
      displacement: "5.0L",
      gearing: "10-Speed",
      type: "Automatic",
    },
    bodyStyle: "Truck",
    sizeClass: "Full Size",
    driveType: DriveType.fourByFour,
    imageSrc: f150,
    intrinsicAttributeArray: [6, 4, 7, 2, 5],
  },
];
